version: '2'
services:
  vugell:
    image: knarfeh/vugell
    build: .
    volumes:
      - .:/src
    environment:
      - URL=http://www.aaronsw.com/weblog/fullarchive
      - DAY_TIME_STAMP=2017-12-22
      - CONTENT_IS_MARKDOWN=true
      - CONTENT_SIZE=300
      - ES_HOST_PORT=http://elasticsearch:9200
      - ES_INDEX=aaronsw
      - DEBUG=true
    env_file:
      - envs/secret.env
      - envs/githubissueseebook.env
    networks:
      - default

networks:
  default:
    external:
      name: githubissueseebook_githubissueseebook
