version: '2'
services:
  vugell:
    image: knarfeh/vugell
    build: .
    volumes:
      - .:/src
    environment:
      - URL=https://github.com/kittencup/angular2-ama-cn/issues
      - ES_ID=2017-12-21
      - CONTENT_IS_MARKDOWN=true
      - CONTENT_SIZE=300
      - ES_HOST_PORT=http://elasticsearch:9200
      - DEBUG=true
    env_file:
      - envs/secret.env
      - envs/githubissueseebook.env
    networks:
      - default

networks:
  default:
    external:
      name: githubissueseebook_githubissueseebook
